"""
C.R.U.Y.F.F. — Data Contracts

Pydantic v2 models defining the wire format between WebSocket gateway,
Redis bus, engine workers, and frontend consumers.
"""
from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field, field_validator


# ---------------------------------------------------------------------------
# Ingest
# ---------------------------------------------------------------------------

class TrackingFrame(BaseModel):
    """
    Raw Metrica-style tracking payload.
    22 players × 2 (x, y) = 44 floats, normalised to pitch dimensions [0, 1].

    Optional fields for live-match hardening:
    - ``team_ids``: per-player team label for dynamic partitioning
    - ``velocities``: per-player (vx, vy) for kinematic projection
    - ``ingest_monotonic``: NTP-immune ingestion timestamp (gateway-tagged)
    """
    timestamp: float = Field(..., description="Unix epoch seconds (sub-ms precision)")
    ingest_monotonic: float | None = Field(
        default=None,
        description=(
            "time.monotonic() at WebSocket ingestion — NTP-immune. "
            "Set by the gateway, NOT the tracking provider."
        ),
    )
    coordinates: list[float] = Field(
        ...,
        min_length=44,
        max_length=44,
        description="Flat array: [p0_x, p0_y, p1_x, p1_y, …, p21_x, p21_y]",
    )
    team_ids: list[Literal["home", "away"]] | None = Field(
        default=None,
        min_length=22,
        max_length=22,
        description="Per-player team label.  If absent, falls back to index-based split.",
    )
    velocities: list[float] | None = Field(
        default=None,
        min_length=44,
        max_length=44,
        description="Optional flat [vx0, vy0, …, vx21, vy21] in pitch-units/sec.",
    )

    @field_validator("coordinates")
    @classmethod
    def _validate_coordinate_count(cls, v: list[float]) -> list[float]:
        if len(v) != 44:
            raise ValueError(
                f"Expected exactly 44 floats (22 players × 2), got {len(v)}"
            )
        return v


class PlayerPosition(BaseModel):
    """Single player (x, y) on the normalised pitch."""
    x: float
    y: float


# ---------------------------------------------------------------------------
# Layer 1 — "The Flow" (Topology)
# ---------------------------------------------------------------------------

class TopologicalVoid(BaseModel):
    """
    A β₁ hole in the defensive Rips complex — a passing lane.
    Centroid is derived from the *death triangle* of the persistence interval.
    """
    centroid_x: float = Field(..., description="x of death-triangle centroid")
    centroid_y: float = Field(..., description="y of death-triangle centroid")
    birth: float = Field(..., description="Filtration value where hole appears")
    death: float = Field(..., description="Filtration value where hole is filled")
    persistence: float = Field(..., description="death − birth")
    death_triangle_indices: tuple[int, int, int] = Field(
        ...,
        description="Vertex indices of the 2-simplex that kills the hole",
    )
    stability: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Temporal stability score (0 = first seen, 1 = fully stable)",
    )


# ---------------------------------------------------------------------------
# Layer 2 — "The Pulse" (Biology / BioKinetics)
# ---------------------------------------------------------------------------

class BioKineticAlert(BaseModel):
    """Per-player cognitive / kinetic status."""
    player_id: int = Field(..., ge=0, lt=22)
    scan_frequency: float = Field(
        ..., ge=0.0, description="Head scanning events per second"
    )
    micro_variance: float = Field(
        ..., ge=0.0, description="Kinetic jerk / micro-stutter metric"
    )
    status: Literal["green", "amber", "red"] = "green"


# ---------------------------------------------------------------------------
# Layer 3 — "The Ghost" (Causality / Trajectory Diffusion)
# ---------------------------------------------------------------------------

class GhostTrajectory(BaseModel):
    """Optimal counterfactual run generated by the diffusion model."""
    waypoints: list[PlayerPosition] = Field(
        ..., min_length=2, description="Ordered trajectory waypoints"
    )
    expected_xt: float = Field(
        ..., ge=0.0, description="Expected Threat gained along this trajectory"
    )


# ---------------------------------------------------------------------------
# Composite Output
# ---------------------------------------------------------------------------

class AnalysisResult(BaseModel):
    """
    Complete per-frame analysis envelope broadcast to connected frontends.
    Any layer may be None if its engine has not yet returned for this frame.
    """
    timestamp: float
    voids: list[TopologicalVoid] = Field(default_factory=list)
    bio_alerts: list[BioKineticAlert] = Field(default_factory=list)
    ghost: GhostTrajectory | None = None
